name: Run on Different Operating Systems
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print OS
      run: echo "Running on ${{ runner.os }}"
