name: Run on Different Operating Systems
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print OS
      run: echo "Running on ${{ runner.os }}"
