name: Example Workflow

on:
  push:
    branches:
      - develop

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print .gitignore Path
        run: echo "The .gitignore file is located at ${{ github.workspace }}/.gitignore"

      # Perform other actions or operations on the .gitignore file as needed
